import assert from 'node:assert/strict';
import test from 'node:test';

import { createPlayerBuild, loadBattleData } from '../lib/battle-model.mjs';
import { beginInteractiveBattle, listInteractiveBattleCommands, resolveInteractiveBattleRound } from '../lib/battle-simulator.mjs';
import { auditEquipmentCheckpointC } from '../lib/player-equipment-checkpoint-c.mjs';
import { CHECKPOINT_C_LEGAL_BUILDS } from '../lib/player-legal-builds-checkpoint-c.mjs';
import { eventGrantProducerManifest } from '../lib/player-skill-acquisition-checkpoint-c.mjs';
import { createInitialJourneyState, grantEventSkillFromProducer, learnPlayerSkill, listPlayerSkillStates } from '../lib/player-journey.mjs';
import { loadSkills } from '../lib/fixtures.mjs';
import { loadPlayerSimulationConfig } from '../lib/player-suite.mjs';
import { loadWorldModel } from '../lib/world-model.mjs';

const data=await loadBattleData();const skills=loadSkills();const model=loadWorldModel();const config=loadPlayerSimulationConfig();
const bySkill=new Map(skills.map((skill)=>[skill.id,skill]));const eventManifest=new Map(eventGrantProducerManifest(skills).map((entry)=>[entry.skillId,entry]));const equipmentAudit=auditEquipmentCheckpointC(data);const equipmentAuditById=new Map(equipmentAudit.equipmentRows.map((row)=>[row.equipmentId,row]));
function prerequisites(skill){if(!skill?.prerequisites)return[];return Array.isArray(skill.prerequisites)?skill.prerequisites:String(skill.prerequisites).split(',').map((value)=>value.trim()).filter(Boolean);}
function ensure(root,path){const parts=String(path).split('.');let cursor=root;for(const part of parts.slice(0,-1))cursor=cursor[part]??={};return{cursor,key:parts.at(-1)};}
function satisfyLeaf(state,leaf){let root=leaf.scope==='progress'?state.progress:leaf.scope==='world'?state.worldFlags:leaf.scope==='player'?state.player:null;if(!root)return;const{cursor,key}=ensure(root,leaf.path);const current=cursor[key];switch(leaf.op){case'gte':cursor[key]=Math.max(Number(current??0),Number(leaf.value));break;case'gt':cursor[key]=Math.max(Number(current??0),Number(leaf.value)+1);break;case'lte':cursor[key]=Number(leaf.value);break;case'lt':cursor[key]=Number(leaf.value)-1;break;case'eq':cursor[key]=leaf.value;break;case'isTrue':cursor[key]=true;break;case'isFalse':cursor[key]=false;break;case'contains':{const set=current instanceof Set?current:new Set(Array.isArray(current)?current:[]);set.add(leaf.value);cursor[key]=set;break;}case'containsAny':{const set=current instanceof Set?current:new Set(Array.isArray(current)?current:[]);const values=Array.isArray(leaf.value)?leaf.value:[leaf.value];if(values[0]!==undefined)set.add(values[0]);cursor[key]=set;break;}default:break;}}
function flatten(condition,out=[]){if(condition==null)return out;if(Array.isArray(condition)){for(const entry of condition)flatten(entry,out);return out;}if(typeof condition!=='object')return out;if(condition.when)flatten(condition.when,out);if(condition.all)flatten(condition.all,out);if(condition.any)flatten(condition.any,out);if(condition.not)flatten(condition.not,out);if(condition.scope&&condition.path&&condition.op)out.push(condition);return out;}
function equipState(state,equipmentIds){state.player.equipment={};state.player.inventory.equipment={};for(const id of equipmentIds){const item=data.equipmentById.get(id);assert.ok(item,`missing equipment ${id}`);state.player.inventory.equipment[id]=1;if(item.slot==='mainHand'&&item.grip==='twoHand')delete state.player.equipment.offHand;if(item.slot==='offHand'){const main=data.equipmentById.get(state.player.equipment.mainHand);assert.notEqual(main?.grip,'twoHand',`${id}: two-hand conflict`);}state.player.equipment[item.slot]=id;}}
function fresh(spec){const state=createInitialJourneyState({model,battleData:data,skills,profile:'balanced',tuning:{...config.tuned,manualSkillSelection:true},seed:`build:${spec.id}`});state.player.level=spec.level;state.player.sp=spec.sp.accumulated;state.player.skills=new Set();state.player.visibleSkillIds=new Set();state.player.flagEligibleSkillIds=new Set();equipState(state,spec.equipmentIds);return state;}
function acquirePermanent(state,skillId,seen=new Set()){if(state.player.skills.has(skillId))return;if(seen.has(skillId))throw new Error(`prerequisite cycle in witness ${skillId}`);seen.add(skillId);const skill=bySkill.get(skillId);assert.ok(skill,skillId);for(const id of prerequisites(skill))acquireSkill(state,id,seen);for(const condition of [...flatten(skill.revealConditions),...flatten(skill.eventUnlockConditions),...flatten(skill.learnConditions)])satisfyLeaf(state,condition);const result=learnPlayerSkill(state,data,skills,skillId);assert.equal(result.ok,true,`${skillId}: ${result.reason} ${JSON.stringify(result.reasons??[])}`);seen.delete(skillId);}
function acquireSkill(state,skillId,seen=new Set()){if(state.player.skills.has(skillId))return;const skill=bySkill.get(skillId);assert.ok(skill,`unknown skill ${skillId}`);if(['basic_level_up','flag_unlocked'].includes(skill.acquisitionCode))return acquirePermanent(state,skillId,seen);if(skill.acquisitionCode==='event_granted'){const manifest=eventManifest.get(skillId);assert.ok(manifest?.producerIds?.[0],`${skillId}: event producer`);const result=grantEventSkillFromProducer(state,data,skills,skillId,manifest.producerIds[0]);assert.equal(result.ok,true,`${skillId}: ${result.reason}`);return;}if(skill.acquisitionCode==='equipment_granted'){assert.equal(listPlayerSkillStates(state,data,skills).find((row)=>row.id===skillId)?.active,true,`${skillId}: equipment grant inactive`);return;}throw new Error(`${skillId}: unsupported acquisition ${skill.acquisitionCode}`);}
function effectiveSkillIds(state){const ids=new Set(state.player.skills);for(const equipmentId of Object.values(state.player.equipment)){const item=data.equipmentById.get(equipmentId);if(item?.grantedSkillId)ids.add(item.grantedSkillId);}return[...ids];}
function battleBuild(spec,state){return createPlayerBuild(data,{id:`C-${spec.id}`,name:spec.label,level:spec.level,equipmentIds:Object.values(state.player.equipment),skillIds:effectiveSkillIds(state),baseStats:{maxHp:100_000,maxMp:500,attack:5,defense:500,agility:800,luck:30,physicalPower:3,magicPower:3,magicResistance:500,accuracy:500,evasion:0,critical:0,debuffSuccess:10_000,debuffResistance:500}});}
function chooseCommand(session,skillId,spec){const commands=listInteractiveBattleCommands({data,session}).filter((entry)=>entry.skillId===skillId);assert.ok(commands.length,`${spec.id}: ${skillId} command missing`);const selected=spec.playerGold?commands.find((entry)=>entry.goldCost===250):spec.weatherChoice?commands.find((entry)=>entry.battleWeather===spec.weatherChoice):commands.find((entry)=>entry.available);assert.ok(selected,`${spec.id}: ${skillId} no selectable command ${JSON.stringify(commands.map((c)=>({id:c.actionId,available:c.available,reason:c.disabledReason})))}`);assert.equal(selected.available,true,`${spec.id}: ${selected.disabledReason}`);return selected;}
function execute(session,skillId,spec){const command=chooseCommand(session,skillId,spec);const output=resolveInteractiveBattleRound({data,session,command:{actionId:command.actionId,targetInstanceId:command.targets?.[0]?.instanceId}});assert.equal(output.ok,true,`${spec.id}: execute ${skillId} ${output.reason}`);return output;}
function playerFrame(output,skillId){return output.round?.frames?.find((frame)=>frame.actorSide==='player'&&frame.action?.skillId===skillId);}
function reactionDamageFrame(output){return output.round?.frames?.find((entry)=>entry.actorSide==='enemy'&&(entry.effects??[]).some((effect)=>effect.targetInstanceId===entry.actorInstanceId&&Number(effect.hpAfter)<Number(effect.hpBefore)));}
function substituteIntercept(output){return output?.round?.frames?.find((entry)=>entry.actorSide==='enemy'&&(entry.events??[]).some((event)=>event.family==='SUBSTITUTE'&&event.consumed===true&&Number(event.interceptedDamage)>0));}

for(const spec of CHECKPOINT_C_LEGAL_BUILDS)test(`Checkpoint C legal build: ${spec.label}`,()=>{
  assert.equal(spec.sp.accumulated-spec.sp.used,spec.sp.remaining,`${spec.id}: SP arithmetic`);assert.ok(spec.level>=1&&spec.level<=30);
  for(const id of [...spec.equipmentIds,...(spec.upgradeEquipmentIds??[])]){const row=equipmentAuditById.get(id);assert.ok(row,`${spec.id}: ${id}`);assert.equal(row.valid,true,`${spec.id}: ${id} world inaccessible`);}
  const state=fresh(spec);const initialSp=state.player.sp;for(const id of spec.acquireSkillIds)acquireSkill(state,id);const actualSpent=initialSp-state.player.sp;assert.equal(actualSpent,spec.sp.used,`${spec.id}: hand-written SP budget mismatch`);assert.equal(state.player.sp,spec.sp.remaining);
  if(spec.id==='virtue-guardian-breaker'){assert.equal(state.player.level,23);assert.equal(state.player.skills.size,11);assert.deepEqual(spec.equipmentIds,['EQP-W-0301','EQP-S-0001']);assert.deepEqual(spec.upgradeEquipmentIds,['EQP-W-0302','EQP-S-0001']);}
  const build=battleBuild(spec,state);assert.equal(build.level,spec.level);const monsterId=spec.reactionSkillId?'MON-0005':'MON-0077';let session=beginInteractiveBattle({data,seed:`checkpoint-c-build:${spec.id}`,monsterIds:[monsterId],playerBuild:build,playerGold:spec.playerGold??500,maxTurns:10});
  if(spec.setupSkillIds)for(const skillId of spec.setupSkillIds){const out=execute(session,skillId,spec);session=out.session;}
  const before={hp:session.state.players[0].hp,mp:session.state.players[0].mp,gold:session.playerRuntimeMechanics.gold,enemyHp:session.state.enemies[0].hp};const output=execute(session,spec.witnessSkillId,spec);session=output.session;const frame=playerFrame(output,spec.witnessSkillId);assert.ok(frame,`${spec.id}: authoritative player frame`);
  if(spec.id==='virtue-guardian-breaker'||spec.id==='two-hand-burst')assert.ok(Number(frame.damage)>=0);
  if(spec.id==='bow-trap')assert.ok(session.playerRuntimeMechanics.traps.length>0);
  if(spec.id==='poison-debuff')assert.ok(session.state.enemies.some((enemy)=>enemy.debuffs.has('poison')),'poison must mutate target');
  if(spec.id==='offensive-caster'){assert.ok(Number(frame.damage)>0,'provisional fire semantics must deal authoritative damage');assert.ok(session.state.enemies.some((enemy)=>Number(enemy.modifiers.get('accuracy')?.stage??0)<=-2),'灰燼の息 must apply accuracy -2');}
  if(spec.id==='grimoire-control')assert.ok((frame.events??[]).some((event)=>event.family==='MAGIC_SUPPRESSION'),'control family event');
  if(spec.id==='summoner'){const summon=session.playerRuntimeMechanics.summons.at(-1);assert.ok(summon);assert.ok(Number(summon.hp)>0,'summon HP');}
  if(spec.id==='doll-substitute'){assert.ok((frame.events??[]).some((event)=>event.family==='SUBSTITUTE'&&event.charges===1),'substitute must be created');let intercept=substituteIntercept(output);for(let attempts=0;!intercept&&session.status==='active'&&attempts<3;attempts+=1){const follow=resolveInteractiveBattleRound({data,session,command:{actionId:'DEFEND'}});assert.equal(follow.ok,true,`${spec.id}: follow-up defend ${follow.reason}`);session=follow.session;intercept=substituteIntercept(follow);}assert.ok(intercept,'substitute must authoritatively absorb the next enemy hit regardless of initiative order');}
  if(spec.id==='formation-explosion'){assert.equal(session.playerRuntimeMechanics.fields.length,0);assert.ok((frame.events??[]).some((event)=>event.family==='CONSUME_OWNED_FIELD'));}
  if(spec.id==='hp-sacrifice')assert.ok(session.state.players[0].hp<before.hp,'HP cost must be real');
  if(spec.id==='mp-bankruptcy'){assert.equal(session.state.players[0].mp,0,'all-current MP cost');assert.ok(Number(session.state.players[0].modifiers.get('magic_power')?.stage??0)>0,'炉心解放 must raise magic power without refunding MP');assert.ok((frame.events??[]).some((event)=>event.family==='RESOURCE_TECHNIQUE'&&event.mpAfter===0),'resource technique runtime event');const hpBefore=session.state.players[0].hp;const out2=execute(session,spec.secondaryWitnessSkillId,spec);assert.ok(out2.session.state.players[0].hp<hpBefore,'missing MP must bridge to HP');session=out2.session;}
  if(spec.id==='luck-gambling'){assert.ok(Number(frame.damage)>0);assert.ok((frame.events??[]).some((event)=>event.family==='LUCK_SCALING'));}
  if(spec.id==='gold-burn'){assert.equal(session.playerRuntimeMechanics.gold,750);assert.ok((frame.events??[]).some((event)=>event.family==='GOLD_SPEND_SCALING'));}
  if(spec.id==='weather-field'){assert.equal(session.playerRuntimeMechanics.weather?.type,'rain');assert.equal(session.playerRuntimeMechanics.weather?.battleLocalOnly,true);assert.equal(session.playerRuntimeMechanics.weather?.worldWeatherMutation,false);}
  if(spec.reactionSkillId){const reaction=bySkill.get(spec.reactionSkillId);assert.ok(reaction);assert.ok(['reaction','passive'].includes(reaction.kind));assert.ok(reactionDamageFrame(output),`${spec.id}: reaction must damage attacking enemy in authoritative enemy frame`);}
});
