import fs from 'node:fs/promises';import crypto from 'node:crypto';import {buildGenerated,itemIdFor} from './gimmickGenerator.js';import {GAME_VERSION,STAGE_VERSION,PHYSICS_VERSION,GENERATOR_VERSION,PROMPT_VERSION} from './gimmickBuilder.js';import * as db from './sheets.js';
const INITIAL=['🦵','🚀','💨','🥅','🏃','🇯🇵'];function user(socket){return socket.data.username&&socket.data.username!=='guest'?socket.data.username:(socket.data.clientId||socket.id||'名無し')}
const ok=(cb,p)=>typeof cb==='function'&&cb({ok:true,...p}); const bad=(cb,e)=>typeof cb==='function'&&cb({ok:false,error:String(e?.message||e)});
async function catalog(){return JSON.parse(await fs.readFile('public/noHand_soccer/emoji_catalog_full_ja.json','utf8'))}
function def(name){return {userName:name,ideaPoints:120,ownedEmojisJson:'[]',ownedGimmickIdsJson:'[]',tutorialState:'intro',tutorialDone:false,stageProgressJson:'{}',updatedAt:new Date().toISOString()}}
async function state(name){return await db.getUser(name)||await db.saveUser(def(name))}
function parse(a,f){try{return JSON.parse(a||'')}catch{return f}}
async function saveState(s){s.updatedAt=new Date().toISOString();await db.saveUser(s);return s}
export function registerNoHandSoccerSocketHandlers(socket){db.ensureSheets();
 socket.on('noHand:getCatalog',async(_,cb)=>{try{ok(cb,{catalog:await catalog()})}catch(e){bad(cb,e)}});
 socket.on('noHand:getUserState',async(_,cb)=>{try{ok(cb,{state:await state(user(socket)),versions:{GAME_VERSION,STAGE_VERSION,PHYSICS_VERSION,GENERATOR_VERSION,PROMPT_VERSION}})}catch(e){bad(cb,e)}});
 socket.on('noHand:updateUserState',async(p,cb)=>{try{const s=await state(user(socket)); if(p?.tutorialState)s.tutorialState=p.tutorialState; if(typeof p?.tutorialDone==='boolean')s.tutorialDone=p.tutorialDone; if(p?.stageProgressJson)s.stageProgressJson=p.stageProgressJson; ok(cb,{state:await saveState(s)})}catch(e){bad(cb,e)}});
 socket.on('noHand:receiveInitialEmojis',async(_,cb)=>{try{const s=await state(user(socket));const owned=new Set(parse(s.ownedEmojisJson,[]));INITIAL.forEach(e=>owned.add(e));s.ownedEmojisJson=JSON.stringify([...owned]);ok(cb,{state:await saveState(s),emojis:INITIAL})}catch(e){bad(cb,e)}});
 socket.on('noHand:buyEmojis',async(p,cb)=>{try{const s=await state(user(socket));const cat=await catalog();const owned=new Set(parse(s.ownedEmojisJson,[]));const em=[...(p?.emojis||[])].filter(x=>cat.some(c=>c.emoji===x)&&!owned.has(x));const total=em.reduce((a,e)=>a+Number(cat.find(c=>c.emoji===e)?.price||0),0);if(total>Number(s.ideaPoints))throw Error('発想ポイントが足りません');em.forEach(e=>owned.add(e));s.ideaPoints=Number(s.ideaPoints)-total;s.ownedEmojisJson=JSON.stringify([...owned]);ok(cb,{state:await saveState(s)})}catch(e){bad(cb,e)}});
 socket.on('noHand:generateGimmick',async(p,cb)=>{try{const emojiArray=Array.isArray(p?.emojiArray)?p.emojiArray:[]; if(emojiArray.length<1||emojiArray.length>3)throw Error('絵文字は1〜3個');const s=await state(user(socket));const owned=new Set(parse(s.ownedEmojisJson,[]));if(!emojiArray.every(e=>owned.has(e)))throw Error('未所持の絵文字があります');const id=itemIdFor(emojiArray);let row=await db.getGimmick(id); if(!row){const cat=await catalog();const info=emojiArray.map(e=>{const c=cat.find(x=>x.emoji===e)||{emoji:e,name:e,jaName:e};return {emoji:c.emoji,name:c.name,jaName:c.jaName}});const gen=await buildGenerated(emojiArray,info);row={itemId:id,emojiSequence:emojiArray.join(''),emojiArrayJson:JSON.stringify(emojiArray),promptVersion:PROMPT_VERSION,generatorVersion:GENERATOR_VERSION,physicsVersion:PHYSICS_VERSION,selectionJson:JSON.stringify(gen.final.selection),finalGimmickJson:JSON.stringify(gen.final),visualLabel:gen.final.visualLabel,imageId:gen.final.imageId,imagePath:gen.final.imagePath,usageCount:0};await db.saveGimmick(row)}const ids=new Set(parse(s.ownedGimmickIdsJson,[]));if(!ids.has(id)){const free=!!p?.tutorialFree && !s.tutorialFreeGenerated;if(!free){if(Number(s.ideaPoints)<30)throw Error('発想ポイントが足りません');s.ideaPoints=Number(s.ideaPoints)-30}else s.tutorialFreeGenerated=true;ids.add(id);s.ownedGimmickIdsJson=JSON.stringify([...ids]);await saveState(s)}ok(cb,{gimmick:JSON.parse(row.finalGimmickJson),state:s,cached:row.usageCount>0})}catch(e){bad(cb,e)}});
 socket.on('noHand:getOwnedGimmicks',async(_,cb)=>{try{const s=await state(user(socket));const ids=parse(s.ownedGimmickIdsJson,[]);const items=[];for(const id of ids){const r=await db.getGimmick(id);if(r)items.push(JSON.parse(r.finalGimmickJson))}ok(cb,{gimmicks:items})}catch(e){bad(cb,e)}});
 socket.on('noHand:awardPoints',async(p,cb)=>{try{const s=await state(user(socket));s.ideaPoints=Number(s.ideaPoints||0)+Number(p?.points||0);ok(cb,{state:await saveState(s)})}catch(e){bad(cb,e)}});
 socket.on('noHand:submitRanking',async(p,cb)=>{try{const base={userName:user(socket)||'名無し',stageId:p.stageId||'stage1',clearTime:Number(p.clearTime),usedCost:Number(p.usedCost),gimmickIdsJson:JSON.stringify(p.gimmickIds||[]),placementsJson:JSON.stringify(p.placements||[]),replayId:p.replayId||'',createdAt:new Date().toISOString()};for(const rankingType of ['time','cost'])await db.addRanking({rankingId:crypto.randomUUID(),rankingType,...base});ok(cb,{})}catch(e){bad(cb,e)}});
 socket.on('noHand:getRankings',async(p,cb)=>{try{ok(cb,{rankings:await db.listRankings(p?.stageId||'stage1',p?.rankingType||'time')})}catch(e){bad(cb,e)}});
 socket.on('noHand:saveReplay',async(p,cb)=>{try{const r={replayId:crypto.randomUUID(),userName:user(socket)||'名無し',stageId:p.stageId||'stage1',runId:p.runId,stageVersion:STAGE_VERSION,physicsVersion:PHYSICS_VERSION,seed:p.seed,placements:p.placements||[],initialState:p.initialState||{},result:p.result||{},createdAt:new Date().toISOString()};await db.saveReplay(r);ok(cb,{replay:r})}catch(e){bad(cb,e)}});
 socket.on('noHand:getReplay',async(p,cb)=>{try{ok(cb,{replay:await db.getReplay(p?.replayId)})}catch(e){bad(cb,e)}})}
