import fs from 'node:fs/promises';import path from 'node:path';import {getSheetsClient} from '../../foundation/sheets.js';import {SPREADSHEET_ID} from '../../foundation/env.js';
const DATA=path.join(process.cwd(),'data/noHandSoccer/store.json');
const DATA_SHEET='素手以外セーフ', RANK_SHEET='素手以外セーフ_ランキング';
const DATA_HEADERS=['recordType','primaryKey','secondaryKey','userName','itemId','emojiSequence','emojiArrayJson','payloadJson','createdAt','updatedAt'];
const RANK_HEADERS=['rankingId','stageId','rankingType','userName','clearTime','usedCost','gimmickIdsJson','placementsJson','replayId','createdAt'];
let sheetsOk=false;
async function read(){try{return JSON.parse(await fs.readFile(DATA,'utf8'))}catch{return {records:[],rankings:[]}}} async function write(d){await fs.mkdir(path.dirname(DATA),{recursive:true});await fs.writeFile(DATA,JSON.stringify(d,null,2))}
async function ensureHeader(client,title,headers){const res=await client.spreadsheets.values.get({spreadsheetId:SPREADSHEET_ID,range:`'${title}'!1:1`});const cur=res.data.values?.[0]||[];const vals=[...cur];for(const h of headers)if(!vals.includes(h))vals.push(h);if(vals.length!==cur.length)await client.spreadsheets.values.update({spreadsheetId:SPREADSHEET_ID,range:`'${title}'!1:1`,valueInputOption:'RAW',requestBody:{values:[vals]}})}
export async function ensureSheets(){try{const client=await getSheetsClient();const meta=await client.spreadsheets.get({spreadsheetId:SPREADSHEET_ID});const existing=new Set((meta.data.sheets||[]).map(s=>s.properties.title));const requests=[DATA_SHEET,RANK_SHEET].filter(s=>!existing.has(s)).map(title=>({addSheet:{properties:{title}}}));if(requests.length)await client.spreadsheets.batchUpdate({spreadsheetId:SPREADSHEET_ID,requestBody:{requests}});await ensureHeader(client,DATA_SHEET,DATA_HEADERS);await ensureHeader(client,RANK_SHEET,RANK_HEADERS);sheetsOk=true}catch(e){sheetsOk=false;console.warn('[noHand] Google Sheets unavailable; development fallback local JSON is active. Production saves should use Sheets.',e.message)}};
function toUser(rec){const p=JSON.parse(rec.payloadJson||'{}');return {userName:rec.userName||rec.primaryKey,...p,ownedEmojisJson:JSON.stringify(p.ownedEmojis||[]),ownedGimmickIdsJson:JSON.stringify(p.ownedGimmickIds||[]),stageProgressJson:JSON.stringify(p.stageProgress||{})}}
function payloadFromUser(u){return {ideaPoints:Number(u.ideaPoints||0),ownedEmojis:JSON.parse(u.ownedEmojisJson||'[]'),ownedGimmickIds:JSON.parse(u.ownedGimmickIdsJson||'[]'),tutorialState:u.tutorialState||'intro',tutorialDone:!!u.tutorialDone,tutorialFreeGenerated:!!u.tutorialFreeGenerated,stageProgress:JSON.parse(u.stageProgressJson||'{}')}}
async function upsertRecord(row){const d=await read();const i=d.records.findIndex(r=>r.recordType===row.recordType&&r.primaryKey===row.primaryKey);i>=0?d.records[i]={...d.records[i],...row,updatedAt:new Date().toISOString()}:d.records.push({...row,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});await write(d)}
export async function getUser(userName){const d=await read();const r=d.records.find(x=>x.recordType==='USER'&&x.primaryKey===userName);return r&&toUser(r)}
export async function saveUser(u){await upsertRecord({recordType:'USER',primaryKey:u.userName,userName:u.userName,payloadJson:JSON.stringify(payloadFromUser(u))});return u}
export async function getGimmick(id){const d=await read();const r=d.records.find(x=>x.recordType==='GIMMICK'&&x.primaryKey===id);if(!r)return null;const p=JSON.parse(r.payloadJson||'{}');return {itemId:id,emojiSequence:r.emojiSequence,emojiArrayJson:r.emojiArrayJson,selectionJson:JSON.stringify(p.selectionJson||{}),finalGimmickJson:JSON.stringify(p.finalGimmickJson||{}),visualLabel:p.visualLabel,imageId:p.imageId,imagePath:p.imagePath,usageCount:p.usageCount||0}}
export async function saveGimmick(row){const old=await getGimmick(row.itemId);const p={selectionJson:JSON.parse(row.selectionJson||'{}'),finalGimmickJson:JSON.parse(row.finalGimmickJson||'{}'),visualLabel:row.visualLabel,imageId:row.imageId,imagePath:row.imagePath,promptVersion:row.promptVersion,generatorVersion:row.generatorVersion,physicsVersion:row.physicsVersion,usageCount:(old?.usageCount||0)+1};await upsertRecord({recordType:'GIMMICK',primaryKey:row.itemId,itemId:row.itemId,emojiSequence:row.emojiSequence,emojiArrayJson:row.emojiArrayJson,payloadJson:JSON.stringify(p)})}
export async function saveReplay(r){await upsertRecord({recordType:'REPLAY',primaryKey:r.replayId,secondaryKey:r.stageId,userName:r.userName,payloadJson:JSON.stringify(r)});return r} export async function getReplay(id){const d=await read();const r=d.records.find(x=>x.recordType==='REPLAY'&&x.primaryKey===id);return r&&JSON.parse(r.payloadJson||'{}')}
export async function addRanking(r){const d=await read();d.rankings.push(r);await write(d)} export async function listRankings(stageId,type){const d=await read();return d.rankings.filter(r=>r.stageId===stageId&&r.rankingType===type).sort((a,b)=>type==='cost'?(a.usedCost-b.usedCost)||(a.clearTime-b.clearTime):a.clearTime-b.clearTime).slice(0,50)}
